@startuml
!include <C4/C4_Context>
Person(gamer, "Gamer")
System(main, "NoTime2Play")
System(backend, "Backend")
System(email, "Email Service")

Rel(gamer, main, "uses", "create account, view profiles, create schedules")
Rel(email, gamer, "send emails", "confirm/reset password")
Rel(backend, email, "send password confirmations")
Rel(main, backend, "uses", "All logic")


@enduml