@startuml
!include <C4/C4_Container>
Person(user, "User")

Container(webapp,"Web App","React App")
System_Boundary(c1, "Application"){
Container(gateway,"Api Gateway","Zull/Spring Gateway")
Container(security,"Auth Service","Oauth2")
Container(application, "Application", "Domain")
ContainerDb(database, "Database")
}

System(email, "Email Service")

Rel(user, webapp, "uses")
Rel(webapp, gateway, "calls", "https")
Rel(gateway, application, "pass traffic")
Rel_L(gateway, security, "uses")
Rel_L(application, database, "uses")
Rel(application, email, "sends messages")
Rel(user, email, "sends messages")
@enduml